#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys


def activate_virtualenv():
    """Activate virtual environment if available."""
    virtualenv = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'venv', 'bin', 'activate_this.py')
    if os.path.exists(virtualenv):
        exec(open(virtualenv).read(), dict(__file__=virtualenv))


def main():
    """Run administrative tasks."""
    activate_virtualenv()
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dcrm.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
